# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='startedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
