# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160829_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='columns',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='game',
            name='diffculty',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='rows',
            field=models.IntegerField(default=9),
        ),
    ]
